name: taxify_apps
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.14.0
  email_validator: ^2.1.17
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  google_maps_flutter: ^2.3.0
  google_maps_flutter_web: ^0.5.4+1
  image_picker: ^1.0.4
  intl: ^0.18.1
  location: ^5.0.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dashboard.png
    - assets/logo.png
    - assets/shania.jpeg
    - assets/taxi.png
    - assets/vione.jpeg
